apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: podinfo-cbx.australiaeast.cloudapp.azure.com
    http:
      paths:
       - path: /
         backend:
          serviceName: podinfo
          servicePort: 9898
