apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: ingress-public
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
        path: /
    # host: podinfoxxxxxxxx.australiaeast.cloudapp.azure.com
